---
name: "Test stuff"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  test-stuff:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        env:
          GITHUB_TOKEN: ${{ secrets.PUSHY_PUSH }}
        run: |
          gh repo clone $GITHUB_REPOSITORY src/
          cd src/
          git status
          git remote -v
