---
name: "Test stuff"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  test-stuff:
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ secrets.PUSHY_PUSH }}
    steps:
      - name: Clone
        run: |
          gh repo clone $GITHUB_REPOSITORY ./src

      - name: Config
        working-directory: ./src
        run: |
          git config user.name "AK (bot)"
          git config user.email "bot@achkts.xyz"

      - name: Edit
        working-directory: ./src
        run: |
          tmpfile=$(mktemp ./randfile-XXX)
          echo "${RANDOM}" > tmpfile

      - name: Commit and open PR
        working-directory: ./src
        run: |
          branch="new-file-$(date +%s)"
          git checkout -b "${branch}"
          git add .
          git commit -m "Adding new randfile"
          git push -f origin "${branch}"
          gh pr create --base main --fill-first --head origin/"${branch}"
